import type { Metadata } from "next";
import localFont from "next/font/local";


import "./globals.css";
import FloatingMenuButton from "../components/floatingMenuButton";



export const metadata: Metadata = {
  title: "Ousman Jobe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link type="text/css" rel="stylesheet" href="css/lightgallery-bundle.css" />
      </head>
      <body
      >
        <FloatingMenuButton />
        {children}
      </body>
    </html>
  );
}
